import { MotionGraphicTemplate } from '../types/motionGraphics';

export const MOTION_GRAPHIC_TEMPLATES: MotionGraphicTemplate[] = [
  // --- LOWER THIRDS ---
  {
    id: 'lt-minimal-clean',
    name: 'Minimal Modern Split',
    category: 'lower-third',
    description: 'Clean split-line lower third with neon cyan accent bar.',
    badge: 'TRENDING',
    bgGradient: 'from-cyan-950 via-slate-900 to-zinc-950',
    accentColor: '#06B6D4',
    defaultParams: {
      title: 'ALEX RIVERA',
      subtitle: 'Creative Director & Filmmaker',
      accentColor: '#06B6D4',
      secondaryColor: '#3B82F6',
      backgroundColor: 'rgba(10, 10, 15, 0.88)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 22,
      scale: 1.0,
      x: 20,
      y: 82,
      opacity: 1.0,
      animationStyle: 'slide',
      durationInSeconds: 4.0,
    },
  },
  {
    id: 'lt-broadcast-news',
    name: 'Broadcast News Bar',
    category: 'lower-third',
    description: 'CNN / BBC style news lower banner with LIVE indicator.',
    badge: 'HOT',
    bgGradient: 'from-red-950 via-slate-900 to-black',
    accentColor: '#EF4444',
    defaultParams: {
      title: 'SPECIAL REPORT',
      subtitle: 'Market rally reaches all-time high',
      handle: 'LIVE',
      accentColor: '#EF4444',
      secondaryColor: '#F59E0B',
      backgroundColor: 'rgba(18, 18, 22, 0.92)',
      textColor: '#FFFFFF',
      fontFamily: 'Montserrat',
      fontSize: 20,
      scale: 1.0,
      x: 30,
      y: 85,
      opacity: 1.0,
      animationStyle: 'slide',
      durationInSeconds: 5.0,
    },
  },
  {
    id: 'lt-cyber-hud',
    name: 'Cyberpunk Tech HUD',
    category: 'lower-third',
    description: 'Futuristic sci-fi tech bracket with animated scanline.',
    badge: 'PRO',
    bgGradient: 'from-purple-950 via-cyan-950 to-black',
    accentColor: '#8B5CF6',
    defaultParams: {
      title: 'CYBER//UNIT_07',
      subtitle: 'Acoustic Signal Detected',
      accentColor: '#8B5CF6',
      secondaryColor: '#00F0FF',
      backgroundColor: 'rgba(5, 5, 12, 0.9)',
      textColor: '#00F0FF',
      fontFamily: 'Syne',
      fontSize: 22,
      scale: 1.0,
      x: 24,
      y: 80,
      opacity: 1.0,
      animationStyle: 'glitch',
      durationInSeconds: 4.5,
    },
  },
  {
    id: 'lt-luxury-serif',
    name: 'Luxury Editorial Gold',
    category: 'lower-third',
    description: 'Elegant golden dual-line serif banner for high-end cinematic videos.',
    badge: 'PRO',
    bgGradient: 'from-amber-950 via-stone-900 to-neutral-950',
    accentColor: '#F59E0B',
    defaultParams: {
      title: 'ELEANOR VANCE',
      subtitle: 'ARCHITECTURAL DIGEST',
      accentColor: '#F59E0B',
      secondaryColor: '#D97706',
      backgroundColor: 'rgba(15, 12, 8, 0.85)',
      textColor: '#FDE68A',
      fontFamily: 'Playfair Display',
      fontSize: 24,
      scale: 1.0,
      x: 25,
      y: 82,
      opacity: 1.0,
      animationStyle: 'fade',
      durationInSeconds: 4.0,
    },
  },
  {
    id: 'lt-social-handle',
    name: 'Creator Social Pill',
    category: 'lower-third',
    description: 'Creator social media handle with blue verified badge.',
    badge: 'TRENDING',
    bgGradient: 'from-sky-950 via-indigo-950 to-slate-900',
    accentColor: '#38BDF8',
    defaultParams: {
      title: '@captionforge',
      subtitle: 'Follow on Instagram & TikTok',
      handle: '✓ VERIFIED',
      accentColor: '#38BDF8',
      secondaryColor: '#6366F1',
      backgroundColor: 'rgba(15, 23, 42, 0.9)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 20,
      scale: 1.0,
      x: 22,
      y: 82,
      opacity: 1.0,
      animationStyle: 'pop',
      durationInSeconds: 3.5,
    },
  },

  // --- TITLES & KINETIC INTROS ---
  {
    id: 'title-cinematic-glitch',
    name: 'Cinematic Kinetic Glitch',
    category: 'title',
    description: 'High impact kinetic intro title with RGB split aberration.',
    badge: 'HOT',
    bgGradient: 'from-red-950 via-purple-950 to-slate-950',
    accentColor: '#F43F5E',
    defaultParams: {
      title: 'THE REVOLUTION',
      subtitle: 'A NEW GENERATION OF CREATORS',
      accentColor: '#F43F5E',
      secondaryColor: '#06B6D4',
      backgroundColor: 'transparent',
      textColor: '#FFFFFF',
      fontFamily: 'Oswald',
      fontSize: 48,
      scale: 1.2,
      x: 50,
      y: 50,
      opacity: 1.0,
      animationStyle: 'glitch',
      durationInSeconds: 3.5,
    },
  },
  {
    id: 'title-stagger-bold',
    name: 'Modern Staggered Box',
    category: 'title',
    description: 'Bold staggered typography with animated sliding accent block.',
    badge: 'TRENDING',
    bgGradient: 'from-emerald-950 via-teal-950 to-slate-950',
    accentColor: '#10B981',
    defaultParams: {
      title: 'SUMMER VIBES',
      subtitle: 'EPISODE 04 // BALI DIARIES',
      accentColor: '#10B981',
      secondaryColor: '#34D399',
      backgroundColor: 'rgba(6, 78, 59, 0.4)',
      textColor: '#FFFFFF',
      fontFamily: 'Montserrat',
      fontSize: 42,
      scale: 1.1,
      x: 50,
      y: 48,
      opacity: 1.0,
      animationStyle: 'bounce',
      durationInSeconds: 3.0,
    },
  },
  {
    id: 'title-editorial-minimal',
    name: 'Editorial Outline Frame',
    category: 'title',
    description: 'Minimalist outline frame expanding from center with typography.',
    badge: 'PRO',
    bgGradient: 'from-zinc-900 via-neutral-900 to-black',
    accentColor: '#E4E4E7',
    defaultParams: {
      title: 'PORTFOLIO 2026',
      subtitle: 'VISUAL ARTS & DESIGN',
      accentColor: '#E4E4E7',
      secondaryColor: '#71717A',
      backgroundColor: 'rgba(24, 24, 27, 0.85)',
      textColor: '#FFFFFF',
      fontFamily: 'Syne',
      fontSize: 36,
      scale: 1.0,
      x: 50,
      y: 50,
      opacity: 1.0,
      animationStyle: 'zoom',
      durationInSeconds: 3.5,
    },
  },
  {
    id: 'title-gradient-mesh',
    name: 'Vibrant Mesh Flow',
    category: 'title',
    description: 'Modern TikTok/Reels kinetic multi-gradient headline.',
    badge: 'NEW',
    bgGradient: 'from-fuchsia-950 via-pink-900 to-purple-950',
    accentColor: '#EC4899',
    defaultParams: {
      title: 'GROW FASTER',
      subtitle: '3 Secrets Nobody Told You',
      accentColor: '#EC4899',
      secondaryColor: '#8B5CF6',
      backgroundColor: 'transparent',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 44,
      scale: 1.1,
      x: 50,
      y: 45,
      opacity: 1.0,
      animationStyle: 'pop',
      durationInSeconds: 3.2,
    },
  },

  // --- CALLOUTS & INFO POINTERS ---
  {
    id: 'callout-tech-pointer',
    name: 'Tech Target Pointer',
    category: 'callout',
    description: 'Angled pointer line with glowing target pin and spec data box.',
    badge: 'PRO',
    bgGradient: 'from-blue-950 via-sky-950 to-slate-900',
    accentColor: '#00F0FF',
    defaultParams: {
      title: 'SONY A7S III',
      subtitle: '4K 120FPS 10-BIT 4:2:2',
      accentColor: '#00F0FF',
      secondaryColor: '#38BDF8',
      backgroundColor: 'rgba(12, 22, 38, 0.9)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 18,
      scale: 1.0,
      x: 65,
      y: 40,
      opacity: 1.0,
      animationStyle: 'slide',
      durationInSeconds: 4.0,
    },
  },
  {
    id: 'callout-price-tag',
    name: 'Product Badge & Price',
    category: 'callout',
    description: 'E-commerce price bubble with highlight strike and discount badge.',
    badge: 'HOT',
    bgGradient: 'from-orange-950 via-amber-950 to-slate-900',
    accentColor: '#F97316',
    defaultParams: {
      title: 'SPECIAL OFFER',
      subtitle: 'LIMITED TIME ONLY',
      numberValue: '$49.99',
      accentColor: '#F97316',
      secondaryColor: '#FACC15',
      backgroundColor: 'rgba(28, 14, 6, 0.92)',
      textColor: '#FFFFFF',
      fontFamily: 'Montserrat',
      fontSize: 20,
      scale: 1.0,
      x: 70,
      y: 35,
      opacity: 1.0,
      animationStyle: 'pop',
      durationInSeconds: 4.0,
    },
  },
  {
    id: 'callout-stats-radial',
    name: 'Radial Stat Counter',
    category: 'callout',
    description: 'Animated circular progress indicator with percentage score.',
    badge: 'NEW',
    bgGradient: 'from-emerald-950 via-teal-900 to-black',
    accentColor: '#10B981',
    defaultParams: {
      title: 'CONVERSION RATE',
      subtitle: '+240% increase in 30 days',
      numberValue: '98%',
      accentColor: '#10B981',
      secondaryColor: '#34D399',
      backgroundColor: 'rgba(6, 36, 26, 0.9)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 18,
      scale: 1.0,
      x: 68,
      y: 35,
      opacity: 1.0,
      animationStyle: 'zoom',
      durationInSeconds: 3.5,
    },
  },

  // --- SOCIAL MEDIA CTAS & SUBSCRIBE ---
  {
    id: 'social-yt-subscribe',
    name: 'YouTube Subscribe & Bell',
    category: 'social-cta',
    description: 'Animated YouTube subscribe button with cursor click and bell ring.',
    badge: 'TRENDING',
    bgGradient: 'from-red-950 via-rose-950 to-black',
    accentColor: '#EF4444',
    defaultParams: {
      title: 'SUBSCRIBE',
      subtitle: 'Hit the bell for notifications 🔔',
      handle: 'Channel Name',
      accentColor: '#EF4444',
      secondaryColor: '#F59E0B',
      backgroundColor: 'rgba(24, 24, 27, 0.95)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 18,
      scale: 1.0,
      x: 50,
      y: 80,
      opacity: 1.0,
      animationStyle: 'pop',
      durationInSeconds: 4.0,
    },
  },
  {
    id: 'social-tiktok-follow',
    name: 'TikTok Neon Follow',
    category: 'social-cta',
    description: 'Pulsing follow badge with neon heart like animation.',
    badge: 'HOT',
    bgGradient: 'from-cyan-950 via-fuchsia-950 to-black',
    accentColor: '#00F0FF',
    defaultParams: {
      title: 'FOLLOW FOR PART 2',
      subtitle: '❤️ 45.2K Likes',
      handle: '@creator',
      accentColor: '#00F0FF',
      secondaryColor: '#EC4899',
      backgroundColor: 'rgba(10, 10, 15, 0.92)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 18,
      scale: 1.0,
      x: 50,
      y: 78,
      opacity: 1.0,
      animationStyle: 'bounce',
      durationInSeconds: 3.5,
    },
  },
  {
    id: 'social-ig-like-comment',
    name: 'Instagram 3-Action Pill',
    category: 'social-cta',
    description: 'Floating glassmorphic pill with Like, Comment, and Share icons.',
    badge: 'NEW',
    bgGradient: 'from-pink-950 via-purple-950 to-slate-900',
    accentColor: '#F43F5E',
    defaultParams: {
      title: 'Save & Share with a Friend',
      subtitle: '💬 Drop your thoughts below',
      accentColor: '#F43F5E',
      secondaryColor: '#A855F7',
      backgroundColor: 'rgba(20, 15, 25, 0.9)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 18,
      scale: 1.0,
      x: 50,
      y: 82,
      opacity: 1.0,
      animationStyle: 'slide',
      durationInSeconds: 3.5,
    },
  },

  // --- BADGES & BANNERS ---
  {
    id: 'badge-breaking-news',
    name: 'Breaking News Strobe Banner',
    category: 'badge',
    description: 'Urgent red strobe headline banner for announcements.',
    badge: 'HOT',
    bgGradient: 'from-red-900 via-rose-950 to-black',
    accentColor: '#DC2626',
    defaultParams: {
      title: 'BREAKING NEWS',
      subtitle: 'MAJOR ANNOUNCEMENT TODAY',
      accentColor: '#DC2626',
      secondaryColor: '#FACC15',
      backgroundColor: 'rgba(220, 38, 38, 0.95)',
      textColor: '#FFFFFF',
      fontFamily: 'Montserrat',
      fontSize: 22,
      scale: 1.0,
      x: 50,
      y: 18,
      opacity: 1.0,
      animationStyle: 'pop',
      durationInSeconds: 4.5,
    },
  },
  {
    id: 'badge-chapter-marker',
    name: 'Chapter Indicator Tag',
    category: 'badge',
    description: 'Minimalist corner chapter pill with section title.',
    badge: 'PRO',
    bgGradient: 'from-zinc-900 via-slate-900 to-black',
    accentColor: '#06B6D4',
    defaultParams: {
      title: 'CHAPTER 03',
      subtitle: 'The Strategy Revealed',
      accentColor: '#06B6D4',
      secondaryColor: '#3B82F6',
      backgroundColor: 'rgba(15, 15, 20, 0.88)',
      textColor: '#FFFFFF',
      fontFamily: 'Outfit',
      fontSize: 16,
      scale: 0.9,
      x: 80,
      y: 12,
      opacity: 0.95,
      animationStyle: 'fade',
      durationInSeconds: 4.0,
    },
  },
];
