import { CaptionStyleConfig, TranslationLanguage } from '../types/caption';

export const PRESET_CATEGORIES = ['All', 'VIRAL', 'ANIMATED', 'HIGHLIGHT', 'CLASSIC', 'CREATIVE'] as const;
// Premium Kinetic Library — additive categories (existing PRESET_CATEGORIES preserved for compatibility)
export const KINETIC_CATEGORIES = ['Dynamic', 'Viral', 'Podcast', 'Cinematic', 'Business', 'Educational', 'Minimal'] as const;
export const TEMPLATE_CATEGORIES = [...PRESET_CATEGORIES, ...KINETIC_CATEGORIES] as const;
export const ALL_TEMPLATE_CATEGORIES = ['All', ...KINETIC_CATEGORIES, 'ANIMATED', 'HIGHLIGHT', 'CLASSIC', 'CREATIVE'] as const;

export const SUPPORTED_LANGUAGES: TranslationLanguage[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'auto', name: 'Auto-Detect', nativeName: 'Auto', flag: '✨' },
  { code: 'bn', name: 'Bengali', nativeName: 'Bangla', flag: '🇧🇩' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
];

export const CAPTION_PRESET_STYLES: CaptionStyleConfig[] = [
  // =========================================================================
  // 🌟 TOP VIRAL CREATOR MASTER STYLES (MATCHING USER SCREENSHOTS)
  // =========================================================================
  // 1. Neon Red Lightning Hook (Image 1: NEVER SAY "SAVE THIS VIDEO")
  {
    id: 'viral-hook-neon-red',
    name: 'Neon Red Lightning Hook',
    presetKey: 'viral-hook-neon-red',
    category: 'VIRAL',
    description: 'Heavy white header with bold italic red text enclosed in a glowing red neon frame with lightning spark accents.',
    fontFamily: 'Montserrat',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FF0033',
    secondaryColor: '#FF2A55',
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 1.0)',
    shadowBlur: 14,
    shadowOffsetX: 3,
    shadowOffsetY: 6,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.9,
    backgroundPaddingX: 20,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 12,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 72,
    alignment: 'center',
    maxWordsPerLine: 3,
    lineMode: 'two-line',
    layoutStyle: 'neon-red-hook',
    highlightScale: 1.4,
    animation: 'punch',
    animationIntensity: 4.5,
  },

  // 2. Violet Metallic 3D & Heavy Block (Image 2: ERECTILE DISFUNCTION)
  {
    id: 'viral-hook-purple-metallic',
    name: 'Violet Metallic 3D & Heavy Block',
    presetKey: 'viral-hook-purple-metallic',
    category: 'VIRAL',
    description: 'Glossy 3D violet/purple gradient header paired with giant white block typography and deep drop shadow.',
    fontFamily: 'Montserrat',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.25,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#A855F7',
    secondaryColor: '#C084FC',
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.95)',
    shadowBlur: 16,
    shadowOffsetX: 2,
    shadowOffsetY: 6,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 72,
    alignment: 'center',
    maxWordsPerLine: 3,
    lineMode: 'two-line',
    layoutStyle: 'violet-metallic-3d',
    highlightScale: 1.35,
    animation: 'pop',
    animationIntensity: 4.0,
  },

  // 3. Electric Yellow Gym & Retention Punch (Image 3: SAVE IT FOR YOUR CHEST DAY)
  {
    id: 'viral-fitness-electric-yellow',
    name: 'Electric Yellow Gym Punch',
    presetKey: 'viral-fitness-electric-yellow',
    category: 'VIRAL',
    description: 'High-retention 2-tier fitness style: crisp white line 1 with ultra-saturated electric lime-yellow punch line 2.',
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#E2FD00',
    secondaryColor: '#FACC15',
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 1.0)',
    shadowBlur: 12,
    shadowOffsetX: 3,
    shadowOffsetY: 5,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 6,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    lineMode: 'two-line',
    layoutStyle: 'fitness-yellow-punch',
    highlightScale: 1.3,
    animation: 'mrbeast',
    animationIntensity: 4.0,
  },

  // 4. Crimson 3D Numbers & Cursive Script (Image 4: $30,000 Business)
  {
    id: 'viral-money-red-script',
    name: 'Crimson 3D & Cursive Script',
    presetKey: 'viral-money-red-script',
    category: 'VIRAL',
    description: 'Striking 3D crimson red numeric hook layered over elegant white handwritten brush script.',
    fontFamily: 'Montserrat',
    secondaryFontFamily: 'Caveat',
    fontSize: 60,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#FF1133',
    secondaryColor: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(255, 0, 51, 0.85)',
    shadowBlur: 18,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 70,
    alignment: 'center',
    maxWordsPerLine: 3,
    lineMode: 'two-line',
    layoutStyle: 'money-crimson-script',
    highlightScale: 1.45,
    animation: 'pop',
    animationIntensity: 4.0,
  },

  // 5. Modern Minimalist & Gradient Badge (Image 5: help you Skip ▶)
  {
    id: 'viral-skip-badge-pill',
    name: 'Modern Minimalist & Gradient Badge',
    presetKey: 'viral-skip-badge-pill',
    category: 'VIRAL',
    description: 'Minimalist clean white lowercase text paired with a glowing violet/purple badge container with play icon.',
    fontFamily: 'Inter',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#8B5CF6',
    secondaryColor: '#6366F1',
    strokeColor: '#000000',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#8B5CF6',
    backgroundOpacity: 0.95,
    backgroundPaddingX: 22,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 16,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    lineMode: 'two-line',
    layoutStyle: 'skip-badge-pill',
    highlightScale: 1.35,
    animation: 'pop',
    animationIntensity: 3.5,
  },

  // =========================================================================
  // 1. VIRAL CATEGORY (6 - 10)
  // =========================================================================
  {
    id: 'mrbeast-bold',
    name: 'MrBeast-inspired Bold',
    presetKey: 'mrbeast-bold',
    category: 'VIRAL',
    description: 'Ultra-bold saturated yellow with thick black stroke, hard drop shadow, and snappy impact pop.',
    fontFamily: 'Montserrat',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FFEA00', // Saturated Beast Yellow
    secondaryColor: '#22C55E', // Energetic Emerald Green
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 1.0)',
    shadowBlur: 0,
    shadowOffsetX: 4,
    shadowOffsetY: 6,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'mrbeast',
    animationIntensity: 4.5,
    highlightScale: 1.25,
  },
  {
    id: 'hormozi-bold',
    name: 'Hormozi-inspired Bold',
    presetKey: 'hormozi-bold',
    category: 'VIRAL',
    description: 'Alex Hormozi signature style: ultra-bold all-caps, lime-yellow active word, background contrast pill.',
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.1,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#A3E635', // Hormozi Lime
    secondaryColor: '#FACC15', // Gold accent
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    shadowBlur: 8,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 20,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 72,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'hormozi',
    animationIntensity: 4.0,
    highlightScale: 1.2,
  },
  {
    id: 'bold-pop',
    name: 'Bold Pop',
    presetKey: 'bold-pop',
    category: 'VIRAL',
    description: 'Energetic scale pop with electric cyan punch word and crisp dual outline.',
    fontFamily: 'Poppins',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#00F0FF', // Electric Cyan
    secondaryColor: '#3B82F6',
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(0, 240, 255, 0.6)',
    shadowBlur: 14,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'bold-pop',
    animationIntensity: 4.5,
    highlightScale: 1.35,
  },
  {
    id: 'punch-caption',
    name: 'Punch Caption',
    presetKey: 'punch-caption',
    category: 'VIRAL',
    description: 'Massive active word explosion with vibrant crimson/amber highlight that commands visual focus.',
    fontFamily: 'Montserrat',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FF3B30', // Crimson Punch
    secondaryColor: '#FF9500', // Amber
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(255, 59, 48, 0.75)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 5,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'punch',
    animationIntensity: 5.0,
    highlightScale: 1.4,
  },
  {
    id: 'color-emphasis',
    name: 'Color Emphasis',
    presetKey: 'color-emphasis',
    category: 'VIRAL',
    description: 'Multi-hue emphasis where spoken words dynamically alternate through curated viral color palettes.',
    fontFamily: 'Poppins',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#F8FAFC',
    activeWordColor: '#F59E0B', // Solar Amber
    secondaryColor: '#EC4899', // Hot Pink
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.85)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'color-emphasis',
    animationIntensity: 3.5,
    highlightScale: 1.2,
  },

  // =========================================================================
  // 2. ANIMATED CATEGORY (6 - 12)
  // =========================================================================
  {
    id: 'word-pop',
    name: 'Word Pop',
    presetKey: 'word-pop',
    category: 'ANIMATED',
    description: 'Smooth spring overshoot pop on active words with physics-based deceleration.',
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: '800',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#38BDF8', // Cyan Blue
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    shadowBlur: 8,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'word-pop',
    animationIntensity: 4.0,
    highlightScale: 1.3,
  },
  {
    id: 'bounce-caption',
    name: 'Bounce',
    presetKey: 'bounce-caption',
    category: 'ANIMATED',
    description: 'Subtle vertical parabolic bounce on each active word with natural damping.',
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: '800',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FBBF24', // Warm Amber
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.85)',
    shadowBlur: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'bounce',
    animationIntensity: 3.5,
    highlightScale: 1.15,
  },
  {
    id: 'slide-up',
    name: 'Slide Up',
    presetKey: 'slide-up',
    category: 'ANIMATED',
    description: 'Smooth upward entry transition from bottom with opacity fade-in.',
    fontFamily: 'Inter',
    fontSize: 50,
    fontWeight: '800',
    letterSpacing: 0.5,
    lineHeight: 1.25,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#60A5FA', // Sky Blue
    strokeColor: '#000000',
    strokeWidth: 5,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.7)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 76,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'slide-up',
    animationIntensity: 3.0,
    highlightScale: 1.1,
  },
  {
    id: 'slide-in',
    name: 'Slide In',
    presetKey: 'slide-in',
    category: 'ANIMATED',
    description: 'Horizontal kinetic entry from the left with cubic bezier deceleration.',
    fontFamily: 'Inter',
    fontSize: 50,
    fontWeight: '800',
    letterSpacing: 0.5,
    lineHeight: 1.25,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#34D399', // Mint Green
    strokeColor: '#000000',
    strokeWidth: 5,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.75)',
    shadowBlur: 8,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 76,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'slide-in',
    animationIntensity: 3.0,
    highlightScale: 1.1,
  },
  {
    id: 'dynamic-scale',
    name: 'Dynamic Scale',
    presetKey: 'dynamic-scale',
    category: 'ANIMATED',
    description: 'Dynamic size rhythm where spoken words swell and contract in continuous harmonic motion.',
    fontFamily: 'Montserrat',
    fontSize: 52,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#A855F7', // Vivid Purple
    secondaryColor: '#EC4899',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(168, 85, 247, 0.6)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'dynamic-scale',
    animationIntensity: 4.0,
    highlightScale: 1.35,
  },
  {
    id: 'shake-jitter',
    name: 'Shake / Jitter',
    presetKey: 'shake-jitter',
    category: 'ANIMATED',
    description: 'Controlled micro-jitter and energetic camera vibration for dramatic high-impact punch.',
    fontFamily: 'Montserrat',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#EF4444', // Danger Red
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(239, 68, 68, 0.8)',
    shadowBlur: 12,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'shake',
    animationIntensity: 3.5,
    shakeIntensity: 4,
    highlightScale: 1.2,
  },
  {
    id: 'pop-motion-blur',
    name: 'Pop + Motion Blur',
    presetKey: 'pop-motion-blur',
    category: 'ANIMATED',
    description: 'Ultra-fast kinetic pop with directional motion blur trailing streaks along entry velocity.',
    fontFamily: 'Montserrat',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#06B6D4', // Electric Cyan
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'pop-blur',
    animationIntensity: 4.5,
    hasMotionBlur: true,
    highlightScale: 1.3,
  },

  // =========================================================================
  // 3. HIGHLIGHT CATEGORY (13 - 16)
  // =========================================================================
  {
    id: 'karaoke-lead',
    name: 'Karaoke',
    presetKey: 'karaoke-lead',
    category: 'HIGHLIGHT',
    description: 'True karaoke mode: full sentence stays visible in dimmed white while active spoken word illuminates with glow.',
    fontFamily: 'Montserrat',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FACC15', // Vibrant Gold
    secondaryColor: '#94A3B8', // Dimmed Inactive Gray
    inactiveWordOpacity: 0.4,
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.85)',
    shadowBlur: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'karaoke',
    animationIntensity: 3.5,
    highlightScale: 1.15,
  },
  {
    id: 'word-highlight',
    name: 'Word Highlight',
    presetKey: 'word-highlight',
    category: 'HIGHLIGHT',
    description: 'Clean high-contrast text where each spoken word shines in radiant accent yellow.',
    fontFamily: 'Poppins',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FBBF24', // Warm Amber
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    shadowBlur: 8,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'word-highlight',
    animationIntensity: 3.5,
    highlightScale: 1.15,
  },
  {
    id: 'highlight-box',
    name: 'Highlight Box',
    presetKey: 'highlight-box',
    category: 'HIGHLIGHT',
    description: 'Rounded marker highlighter background box under the active spoken word.',
    fontFamily: 'Montserrat',
    fontSize: 50,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#000000', // Black text inside bright box
    hasHighlightBox: true,
    highlightBoxColor: '#FACC15', // Bright Yellow Marker
    highlightBoxTextColor: '#000000',
    highlightBoxPaddingX: 10,
    highlightBoxPaddingY: 5,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1.0,
    strokeColor: '#000000',
    strokeWidth: 5,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    shadowBlur: 8,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'highlight-box',
    animationIntensity: 3.5,
    highlightScale: 1.05,
  },
  {
    id: 'active-word-color',
    name: 'Active Word Color',
    presetKey: 'active-word-color',
    category: 'HIGHLIGHT',
    description: 'Clean modern typography where only the currently spoken word dynamically switches to an electric blue hue.',
    fontFamily: 'Inter',
    fontSize: 50,
    fontWeight: '800',
    letterSpacing: 0.6,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#38BDF8', // Electric Cyan Blue
    strokeColor: '#000000',
    strokeWidth: 5,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.75)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 75,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'active-color',
    animationIntensity: 3.0,
    highlightScale: 1.1,
  },

  // =========================================================================
  // 4. CLASSIC CATEGORY (17 - 20)
  // =========================================================================
  {
    id: 'cinematic-minimal',
    name: 'Cinematic Minimal',
    presetKey: 'cinematic-minimal',
    category: 'CLASSIC',
    description: 'Clean off-white typography, zero visual clutter, soft shadow, perfect for documentaries, interviews and podcasts.',
    fontFamily: 'Inter',
    fontSize: 44,
    fontWeight: '600',
    letterSpacing: 0.4,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.85)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 2,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 82,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'cinematic',
    animationIntensity: 1.0,
    highlightScale: 1.0,
  },
  {
    id: 'clean-subtitle',
    name: 'Clean Subtitle',
    presetKey: 'clean-subtitle',
    category: 'CLASSIC',
    description: 'High-readability subtitle with semi-transparent dark background box and natural sentence wrapping.',
    fontFamily: 'Inter',
    fontSize: 42,
    fontWeight: '700',
    letterSpacing: 0.2,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#FACC15',
    strokeColor: '#000000',
    strokeWidth: 2,
    hasShadow: false,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowBlur: 4,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.75,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 80,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'clean-sub',
    animationIntensity: 1.5,
    highlightScale: 1.05,
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    presetKey: 'typewriter',
    category: 'CLASSIC',
    description: 'Character-by-character progressive typing animation with animated blinking cursor block.',
    fontFamily: 'Roboto',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: 1.0,
    lineHeight: 1.25,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#38BDF8',
    strokeColor: '#000000',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    shadowBlur: 6,
    shadowOffsetX: 1,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.7,
    backgroundPaddingX: 16,
    backgroundPaddingY: 6,
    backgroundBorderRadius: 6,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 76,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'typewriter',
    animationIntensity: 3.0,
    typewriterSpeed: 25,
    typewriterShowCursor: true,
    highlightScale: 1.0,
  },
  {
    id: 'uppercase-punch',
    name: 'Uppercase Punch',
    presetKey: 'uppercase-punch',
    category: 'CLASSIC',
    description: 'Heavy bold all-caps typography with solid contrast and immediate snappy impact.',
    fontFamily: 'Impact',
    fontSize: 60,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 1.1,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FBBF24', // Punch Amber
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 1.0)',
    shadowBlur: 0,
    shadowOffsetX: 4,
    shadowOffsetY: 5,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'uppercase-punch',
    animationIntensity: 4.0,
    highlightScale: 1.25,
  },

  // =========================================================================
  // 5. CREATIVE CATEGORY (21 - 24)
  // =========================================================================
  {
    id: 'caption-3d',
    name: '3D Caption',
    presetKey: 'caption-3d',
    category: 'CREATIVE',
    description: 'Multi-layered 2.5D/3D extrusion with isometric depth steps, beveled face gradient, and ambient shadow.',
    fontFamily: 'Montserrat',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#38BDF8', // Cyber Blue
    secondaryColor: '#0284C7', // Deep 3D Blue Extrusion
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.95)',
    shadowBlur: 14,
    shadowOffsetX: 3,
    shadowOffsetY: 8,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: '3d',
    animationIntensity: 4.0,
    has3DExtrusion: true,
    depth3D: 8,
    depthColor: '#0369A1',
    highlightScale: 1.25,
  },
  {
    id: 'neon-glow',
    name: 'Neon Caption',
    presetKey: 'neon-glow',
    category: 'CREATIVE',
    description: 'Cyberpunk luminous neon glow with dual-pass radial bloom and saturated core.',
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#00F0FF', // Cyan Core
    strokeColor: '#0891B2',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0, 240, 255, 0.9)',
    shadowBlur: 24,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasLightingGlow: true,
    lightingGlowColor: 'rgba(0, 240, 255, 0.65)',
    lightingGlowRadius: 40,
    lightingGlowIntensity: 0.9,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'neon',
    animationIntensity: 4.5,
    highlightScale: 1.2,
  },
  {
    id: 'glitch-rgb',
    name: 'Glitch Caption',
    presetKey: 'glitch-rgb',
    category: 'CREATIVE',
    description: 'Chromatic aberration RGB channel splitting (Red/Cyan offset) with high-voltage scanline flicker.',
    fontFamily: 'Montserrat',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#00F0FF', // Cyan Channel
    secondaryColor: '#FF0055', // Magenta Red Channel
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(255, 0, 85, 0.75)',
    shadowBlur: 8,
    shadowOffsetX: -3,
    shadowOffsetY: 1,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'glitch',
    animationIntensity: 4.0,
    glitchIntensity: 4,
    highlightScale: 1.2,
  },
  {
    id: 'dynamic-multiline',
    name: 'Dynamic Multi-Line',
    presetKey: 'dynamic-multiline',
    category: 'CREATIVE',
    description: 'Intelligent multi-line phrase partitioning with synchronized line spacing, active word highlight and safe boundaries.',
    fontFamily: 'Montserrat',
    fontSize: 50,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FACC15', // Gold Active Word
    secondaryColor: '#38BDF8',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 72,
    alignment: 'center',
    maxWordsPerLine: 3,
    layoutStyle: 'dynamic-multiline',
    animation: 'multiline',
    animationIntensity: 3.5,
    highlightScale: 1.2,
  },
  {
    id: 'hook-calligraphy-red',
    name: 'Calligraphy Script Hook (Screenshot 1)',
    presetKey: 'hook-calligraphy-red',
    category: 'VIRAL',
    description: 'High-contrast bold white hook text combined with flowing crimson red cursive calligraphy script.',
    fontFamily: 'Montserrat',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#EF4444', // Vivid Red Calligraphy
    secondaryColor: '#DC2626',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(239, 68, 68, 0.65)',
    shadowBlur: 14,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'middle',
    xOffsetPercent: 50,
    yOffsetPercent: 50,
    alignment: 'center',
    maxWordsPerLine: 4,
    layoutStyle: 'dual-tier-hook',
    animation: 'bold-pop',
    animationIntensity: 4.5,
    highlightScale: 1.5,
  },
  {
    id: 'hook-impact-gradient',
    name: 'Impact Giant Hook (Screenshot 2)',
    presetKey: 'hook-impact-gradient',
    category: 'VIRAL',
    description: 'Massive ultra-bold black uppercase header with clean subtitle phrase below.',
    fontFamily: 'Montserrat',
    fontSize: 66,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 1.1,
    casing: 'uppercase',
    textColor: '#000000',
    activeWordColor: '#18181B',
    secondaryColor: '#FFFFFF',
    strokeColor: '#FFFFFF',
    strokeWidth: 5,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.85)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 6,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'middle',
    xOffsetPercent: 50,
    yOffsetPercent: 50,
    alignment: 'center',
    maxWordsPerLine: 4,
    layoutStyle: 'dual-tier-hook',
    animation: 'punch',
    animationIntensity: 4.5,
    highlightScale: 1.6,
  },
  {
    id: 'hook-neon-highlight',
    name: 'Lime Highlighter Box (Screenshot 3)',
    presetKey: 'hook-neon-highlight',
    category: 'HIGHLIGHT',
    description: 'Signature viral highlighter: vibrant neon lime-green rectangle box behind animated keywords.',
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FFFFFF',
    secondaryColor: '#84CC16', // Lime Green 500
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#84CC16',
    backgroundOpacity: 1.0,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 6,
    position: 'middle',
    xOffsetPercent: 50,
    yOffsetPercent: 55,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'highlight-box',
    animationIntensity: 4.0,
    highlightScale: 1.25,
  },

  // =========================================================================
  // 7. ONLINE VIRAL & CREATOR ICONIC TEMPLATES (Premiere Pro & CapCut MOGRTs)
  // =========================================================================
  {
    id: 'iman-gadzhi-luxury',
    name: 'Iman Gadzhi Luxury Serif',
    presetKey: 'iman-gadzhi-luxury',
    category: 'CLASSIC',
    description: 'Cinematic luxury editorial serif with gold-leaf active word highlight, subtle warm glow, and elegant kinetic glide.',
    fontFamily: 'Playfair Display',
    fontSize: 52,
    fontWeight: '700',
    letterSpacing: 1.5,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#D4AF37', // Imperial Gold
    secondaryColor: '#E9D5FF',
    strokeColor: '#000000',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(212, 175, 55, 0.45)',
    shadowBlur: 14,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#09090B',
    backgroundOpacity: 0.75,
    backgroundPaddingX: 20,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'slide-up',
    animationIntensity: 3.5,
    highlightScale: 1.15,
  },
  {
    id: 'ali-abdaal-aesthetic',
    name: 'Ali Abdaal Aesthetic Notion',
    presetKey: 'ali-abdaal-aesthetic',
    category: 'HIGHLIGHT',
    description: 'Modern clean productivity aesthetic with pastel yellow highlighter box marker behind active spoken words.',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 50,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.25,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#0F172A',
    secondaryColor: '#FEF08A',
    strokeColor: '#000000',
    strokeWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.65)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    hasHighlightBox: true,
    highlightBoxColor: '#FEF08A', // Pastel Highlighter Yellow
    highlightBoxTextColor: '#0F172A',
    highlightBoxPaddingX: 10,
    highlightBoxPaddingY: 4,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1.0,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 72,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'word-pop',
    animationIntensity: 3.5,
    highlightScale: 1.1,
  },
  {
    id: 'vox-editorial-typewriter',
    name: 'Vox Investigative Explainer',
    presetKey: 'vox-editorial-typewriter',
    category: 'HIGHLIGHT',
    description: 'Investigative documentary typewriter with punchy yellow marker background strike on key emphasized words.',
    fontFamily: 'Courier Prime',
    fontSize: 52,
    fontWeight: '700',
    letterSpacing: 1.2,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#000000',
    secondaryColor: '#FFE600',
    strokeColor: '#000000',
    strokeWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    shadowBlur: 4,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.95,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 4,
    hasHighlightBox: true,
    highlightBoxColor: '#FFE600', // Editorial Highlighter Yellow
    highlightBoxTextColor: '#000000',
    highlightBoxPaddingX: 8,
    highlightBoxPaddingY: 4,
    highlightBoxRadius: 4,
    highlightBoxOpacity: 1.0,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'punch',
    animationIntensity: 4.0,
    highlightScale: 1.15,
  },
  {
    id: 'devin-jatho-cyan',
    name: 'Devin Jatho Cyan Punch',
    presetKey: 'devin-jatho-cyan',
    category: 'VIRAL',
    description: 'High-retention social hook style with explosive electric cyan active words and heavy outline.',
    fontFamily: 'Montserrat',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#00F0FF', // Electric Cyan
    secondaryColor: '#FF0055', // Hot Magenta
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 240, 255, 0.7)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 5,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'bold-pop',
    animationIntensity: 4.5,
    highlightScale: 1.35,
  },
  {
    id: 'cardone-sales-10x',
    name: 'Grant Cardone 10X Red',
    presetKey: 'cardone-sales-10x',
    category: 'VIRAL',
    description: 'Ultra-bold sales red punch with aggressive white text, thick border and high retention impact pop.',
    fontFamily: 'Montserrat',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FF0000', // 10X Crimson
    secondaryColor: '#FFAA00',
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(255, 0, 0, 0.75)',
    shadowBlur: 18,
    shadowOffsetX: 0,
    shadowOffsetY: 6,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'punch',
    animationIntensity: 5.0,
    highlightScale: 1.4,
  },
  {
    id: 'tiktok-karaoke-glaze',
    name: 'TikTok Trending Karaoke Flow',
    presetKey: 'tiktok-karaoke-glaze',
    category: 'ANIMATED',
    description: 'Word-by-word glowing sweep transition with dimmed slate base text and vibrant mint/neon rose highlights.',
    fontFamily: 'Poppins',
    fontSize: 54,
    fontWeight: '800',
    letterSpacing: 1.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#94A3B8',
    activeWordColor: '#00F5D4', // Vibrant Mint
    secondaryColor: '#FF007F', // Neon Rose
    inactiveWordOpacity: 0.45,
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 245, 212, 0.65)',
    shadowBlur: 14,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#0B0F19',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 20,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 12,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'karaoke',
    animationIntensity: 4.0,
    highlightScale: 1.2,
  },
  {
    id: 'luke-belmar-gold',
    name: 'Luke Belmar Gold Matrix',
    presetKey: 'luke-belmar-gold',
    category: 'VIRAL',
    description: 'High-net-worth aesthetic with pure amber gold typography, dark glass backdrop, and luxury drop shadow.',
    fontFamily: 'Cinzel',
    fontSize: 54,
    fontWeight: '800',
    letterSpacing: 2.0,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#F59E0B', // Pure Amber Gold
    secondaryColor: '#FDE68A',
    strokeColor: '#000000',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(245, 158, 11, 0.6)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 22,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'dynamic-scale',
    animationIntensity: 3.5,
    highlightScale: 1.2,
  },
  {
    id: 'bangla-viral-creator',
    name: 'Bangla Viral Creator',
    presetKey: 'bangla-viral-creator',
    category: 'VIRAL',
    description: 'High-energy golden yellow highlight with deep black stroke for maximum retention.',
    fontFamily: 'Hind Siliguri',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 0.5,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#FFD600', // Saturated Sun Yellow
    secondaryColor: '#22C55E', // Green
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.95)',
    shadowBlur: 12,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'mrbeast',
    animationIntensity: 4.5,
    highlightScale: 1.25,
  },
  {
    id: 'bangla-aesthetic-glass',
    name: 'Bangla Minimal Glass',
    presetKey: 'bangla-aesthetic-glass',
    category: 'HIGHLIGHT',
    description: 'Frosted dark background pill with smooth active word marker and modern aesthetic.',
    fontFamily: 'Noto Sans Bengali',
    fontSize: 50,
    fontWeight: '700',
    letterSpacing: 0.5,
    lineHeight: 1.25,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#6EE7B7', // Soft Emerald
    secondaryColor: '#A7F3D0',
    strokeColor: '#000000',
    strokeWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.7)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 20,
    backgroundPaddingY: 9,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 72,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'word-pop',
    animationIntensity: 3.5,
    highlightScale: 1.15,
  },

  // =========================================================================
  // 6. PREMIERE PRO / AFTER EFFECTS & PINTEREST VIP GLOW TEMPLATES
  // =========================================================================
  {
    id: 'pr-radiant-cyan-glow',
    name: 'Premiere Pro Radiant Cyan',
    presetKey: 'pr-radiant-cyan-glow',
    category: 'VIRAL',
    description: 'Premiere Pro and After Effects style multi-pass cyan neon glow with bold pop energy.',
    fontFamily: 'Montserrat',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#00F0FF',
    secondaryColor: '#A855F7',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 240, 255, 0.95)',
    shadowBlur: 20,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasLightingGlow: true,
    lightingGlowColor: '#00F0FF',
    lightingGlowRadius: 28,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'bold-pop',
    animationIntensity: 4.5,
    highlightScale: 1.3,
  },
  {
    id: 'ae-hyper-gold-luxury',
    name: 'After Effects 24K Hyper Gold',
    presetKey: 'ae-hyper-gold-luxury',
    category: 'VIRAL',
    description: 'Luxury motion graphics 24-karat pure golden glow with sharp contrast.',
    fontFamily: 'Cinzel',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1.8,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFBEB',
    activeWordColor: '#FDE047',
    secondaryColor: '#F59E0B',
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(245, 158, 11, 0.9)',
    shadowBlur: 24,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasLightingGlow: true,
    lightingGlowColor: '#F59E0B',
    lightingGlowRadius: 30,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 73,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'word-pop',
    animationIntensity: 4.0,
    highlightScale: 1.25,
  },
  {
    id: 'pinterest-aesthetic-lilac',
    name: 'Pinterest Aesthetic Lilac',
    presetKey: 'pinterest-aesthetic-lilac',
    category: 'HIGHLIGHT',
    description: 'Trending lilac pastel glow with frosted highlighter pill.',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 50,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#FAF5FF',
    activeWordColor: '#C084FC',
    secondaryColor: '#E9D5FF',
    strokeColor: '#000000',
    strokeWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(192, 132, 252, 0.65)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasLightingGlow: true,
    lightingGlowColor: '#C084FC',
    lightingGlowRadius: 20,
    hasHighlightBox: true,
    highlightBoxColor: '#E9D5FF',
    highlightBoxTextColor: '#581C87',
    highlightBoxPaddingX: 12,
    highlightBoxPaddingY: 5,
    highlightBoxRadius: 8,
    highlightBoxOpacity: 0.95,
    hasBackgroundPill: true,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 20,
    backgroundPaddingY: 9,
    backgroundBorderRadius: 12,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 72,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'highlight-box',
    animationIntensity: 3.5,
    highlightScale: 1.15,
  },
  {
    id: 'pinterest-sunset-neon',
    name: 'Pinterest Sunset Neon',
    presetKey: 'pinterest-sunset-neon',
    category: 'ANIMATED',
    description: 'Viral karaoke sunset rose glow with smooth vocal tracking.',
    fontFamily: 'Poppins',
    fontSize: 54,
    fontWeight: '900',
    letterSpacing: 1.0,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#64748B',
    activeWordColor: '#F43F5E',
    secondaryColor: '#FBBF24',
    inactiveWordOpacity: 0.4,
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(244, 63, 94, 0.85)',
    shadowBlur: 20,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasLightingGlow: true,
    lightingGlowColor: '#F43F5E',
    lightingGlowRadius: 26,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'karaoke',
    animationIntensity: 4.0,
    highlightScale: 1.25,
  },
  {
    id: 'bangla-golden-glow-vip',
    name: 'Golden Glow VIP',
    presetKey: 'bangla-golden-glow-vip',
    category: 'VIRAL',
    description: 'Vibrant golden aura glow with bold cut outline.',
    fontFamily: 'Hind Siliguri',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 0.5,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#FACC15',
    secondaryColor: '#F59E0B',
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(245, 158, 11, 0.95)',
    shadowBlur: 24,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasLightingGlow: true,
    lightingGlowColor: '#F59E0B',
    lightingGlowRadius: 28,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'mrbeast',
    animationIntensity: 4.5,
    highlightScale: 1.25,
  },
  {
    id: 'bangla-cyber-neon',
    name: 'Cyber Neon Glow',
    presetKey: 'bangla-cyber-neon',
    category: 'VIRAL',
    description: 'Futuristic cyberpunk cyan neon bloom with kinetic pop animation.',
    fontFamily: 'Noto Sans Bengali',
    fontSize: 54,
    fontWeight: '900',
    letterSpacing: 0.5,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#22D3EE',
    secondaryColor: '#818CF8',
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(34, 211, 238, 0.9)',
    shadowBlur: 22,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    hasLightingGlow: true,
    lightingGlowColor: '#06B6D4',
    lightingGlowRadius: 24,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'bold-pop',
    animationIntensity: 4.0,
    highlightScale: 1.2,
  },
  {
    id: 'hollywood-3d-punch',
    name: 'Hollywood 3D Extrusion',
    presetKey: 'hollywood-3d-punch',
    category: 'CREATIVE',
    description: 'Cinematic 3D extruded block lettering with deep shadow pop.',
    fontFamily: 'Impact',
    fontSize: 60,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 1.1,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#38BDF8',
    secondaryColor: '#0284C7',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 1.0)',
    shadowBlur: 0,
    shadowOffsetX: 6,
    shadowOffsetY: 8,
    has3DExtrusion: true,
    depth3D: 10,
    depthColor: '#0284C7',
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'punch',
    animationIntensity: 4.5,
    highlightScale: 1.35,
  },

  // =========================================================================
  // PREMIUM KINETIC CAPTION LIBRARY — DYNAMIC, VIRAL, PODCAST, CINEMATIC, BUSINESS, EDUCATIONAL, MINIMAL
  // One-click configurations built on the reusable CaptionStyleConfig engine.
  // =========================================================================

  // --- DYNAMIC (Kinetic Typography) ---
  {
    id: 'dynamic-bold-impact',
    name: 'Dynamic Bold Impact',
    presetKey: 'dynamic-bold-impact',
    category: 'Dynamic',
    description: 'STYLE 01 — Large bold white with strong highlight pop. High-energy word scaling.',
    fontFamily: 'Montserrat',
    fontSize: 60,
    fontWeight: '900',
    letterSpacing: 1.2,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FF3B30',
    secondaryColor: '#FF9500',
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,1)',
    shadowBlur: 0,
    shadowOffsetX: 4,
    shadowOffsetY: 6,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'punch',
    animationIntensity: 5,
    highlightScale: 1.4,
  },
  {
    id: 'dynamic-yellow-emphasis',
    name: 'Dynamic Yellow Emphasis',
    presetKey: 'dynamic-yellow-emphasis',
    category: 'Dynamic',
    description: 'STYLE 02 — White base, yellow active word, fast word-level emphasis.',
    fontFamily: 'Poppins',
    fontSize: 54,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#F8FAFC',
    activeWordColor: '#FACC15',
    secondaryColor: '#F59E0B',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 10,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'word-pop',
    animationIntensity: 4,
    highlightScale: 1.3,
  },
  {
    id: 'dynamic-red-warning',
    name: 'Dynamic Red Warning',
    presetKey: 'dynamic-red-warning',
    category: 'Dynamic',
    description: 'STYLE 03 — Warning red hook with strong entrance slam.',
    fontFamily: 'Montserrat',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#EF4444',
    secondaryColor: '#991B1B',
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(239,68,68,0.7)',
    shadowBlur: 14,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'shake',
    animationIntensity: 4,
    shakeIntensity: 3,
    highlightScale: 1.35,
  },
  {
    id: 'dynamic-bounce',
    name: 'Dynamic Bounce',
    presetKey: 'dynamic-bounce',
    category: 'Dynamic',
    description: 'Bouncy overshoot entrance with lively emphasis.',
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: '900',
    letterSpacing: 1,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FBBF24',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'bounce',
    animationIntensity: 4,
    highlightScale: 1.25,
  },
  {
    id: 'dynamic-word-focus',
    name: 'Dynamic Word Focus',
    presetKey: 'dynamic-word-focus',
    category: 'Dynamic',
    description: 'Active word color + scale emphasis with karaoke dimming.',
    fontFamily: 'Montserrat',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 1,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#94A3B8',
    activeWordColor: '#38BDF8',
    secondaryColor: '#94A3B8',
    inactiveWordOpacity: 0.45,
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 10,
    shadowOffsetX: 1,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#0B0F19',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 18,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'karaoke',
    animationIntensity: 4,
    highlightScale: 1.2,
  },

  // --- VIRAL / SHORTS ---
  {
    id: 'viral-bold',
    name: 'Viral Bold',
    presetKey: 'viral-bold',
    category: 'Viral',
    description: 'Thick stroke viral bold with punchy active scaling.',
    fontFamily: 'Montserrat',
    fontSize: 60,
    fontWeight: '900',
    letterSpacing: 1.3,
    lineHeight: 1.12,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FFEA00',
    secondaryColor: '#22C55E',
    strokeColor: '#000000',
    strokeWidth: 8,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,1)',
    shadowBlur: 0,
    shadowOffsetX: 4,
    shadowOffsetY: 6,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'mrbeast',
    animationIntensity: 4.5,
    highlightScale: 1.35,
  },
  {
    id: 'shorts-punch',
    name: 'Shorts Punch',
    presetKey: 'shorts-punch',
    category: 'Viral',
    description: 'Shorts-native punch with explosive emphasis.',
    fontFamily: 'Poppins',
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 1.1,
    lineHeight: 1.15,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#FF3B30',
    secondaryColor: '#FF9500',
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(255,59,48,0.75)',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 5,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 73,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'punch',
    animationIntensity: 5,
    highlightScale: 1.4,
  },
  {
    id: 'reel-pop',
    name: 'Reel Pop',
    presetKey: 'reel-pop',
    category: 'Viral',
    description: 'Reels kinetic pop with cyan electric word burst.',
    fontFamily: 'Poppins',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: 1,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#06B6D4',
    secondaryColor: '#3B82F6',
    strokeColor: '#000000',
    strokeWidth: 7,
    hasShadow: true,
    shadowColor: 'rgba(6,182,212,0.6)',
    shadowBlur: 14,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'bold-pop',
    animationIntensity: 4.5,
    highlightScale: 1.35,
  },
  {
    id: 'tiktok-energy',
    name: 'TikTok Energy',
    presetKey: 'tiktok-energy',
    category: 'Viral',
    description: 'High-frequency tiktok rhythm with scale wave.',
    fontFamily: 'Inter',
    fontSize: 54,
    fontWeight: '800',
    letterSpacing: 0.6,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#A855F7',
    secondaryColor: '#EC4899',
    strokeColor: '#000000',
    strokeWidth: 6,
    hasShadow: true,
    shadowColor: 'rgba(168,85,247,0.6)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'dynamic-scale',
    animationIntensity: 4,
    highlightScale: 1.35,
  },
  {
    id: 'fast-highlight',
    name: 'Fast Highlight',
    presetKey: 'fast-highlight',
    category: 'Viral',
    description: 'Rapid marker highlight box under active word.',
    fontFamily: 'Montserrat',
    fontSize: 52,
    fontWeight: '900',
    letterSpacing: 1,
    lineHeight: 1.2,
    casing: 'uppercase',
    textColor: '#FFFFFF',
    activeWordColor: '#000000',
    strokeColor: '#000000',
    strokeWidth: 5,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 8,
    shadowOffsetX: 2,
    shadowOffsetY: 4,
    hasHighlightBox: true,
    highlightBoxColor: '#FACC15',
    highlightBoxTextColor: '#000000',
    highlightBoxPaddingX: 10,
    highlightBoxPaddingY: 5,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 3,
    animation: 'highlight-box',
    animationIntensity: 3.5,
    highlightScale: 1.05,
  },

  // --- PODCAST ---
  {
    id: 'podcast-clean',
    name: 'Podcast Clean',
    presetKey: 'podcast-clean',
    category: 'Podcast',
    description: 'STYLE 04 — Clean, minimal, highly readable speaker captions.',
    fontFamily: 'Inter',
    fontSize: 44,
    fontWeight: '600',
    letterSpacing: 0.3,
    lineHeight: 1.35,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#F8FAFC',
    strokeColor: '#000000',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 2,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.75,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 82,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'fade',
    animationIntensity: 1,
    highlightScale: 1,
  },
  {
    id: 'podcast-bold',
    name: 'Podcast Bold',
    presetKey: 'podcast-bold',
    category: 'Podcast',
    description: 'Bold podcast voice with subtle pop.',
    fontFamily: 'Montserrat',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.25,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#FACC15',
    secondaryColor: '#F59E0B',
    strokeColor: '#000000',
    strokeWidth: 5,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.7,
    backgroundPaddingX: 18,
    backgroundPaddingY: 9,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'word-pop',
    animationIntensity: 3,
    highlightScale: 1.15,
  },
  {
    id: 'podcast-highlight',
    name: 'Podcast Highlight',
    presetKey: 'podcast-highlight',
    category: 'Podcast',
    description: 'Pastel marker highlight for key takeaways.',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: 0.5,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#0F172A',
    strokeColor: '#000000',
    strokeWidth: 0,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.65)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasHighlightBox: true,
    highlightBoxColor: '#FEF08A',
    highlightBoxTextColor: '#0F172A',
    highlightBoxPaddingX: 10,
    highlightBoxPaddingY: 4,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1,
    hasBackgroundPill: true,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 76,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'word-highlight',
    animationIntensity: 3,
    highlightScale: 1.1,
  },
  {
    id: 'podcast-speaker',
    name: 'Podcast Speaker',
    presetKey: 'podcast-speaker',
    category: 'Podcast',
    description: 'Two-line speaker focus with name emphasis.',
    fontFamily: 'Inter',
    fontSize: 46,
    fontWeight: '700',
    letterSpacing: 0.4,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#E2E8F0',
    activeWordColor: '#38BDF8',
    secondaryColor: '#0EA5E9',
    strokeColor: '#000000',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 80,
    alignment: 'center',
    maxWordsPerLine: 6,
    lineMode: 'two-line',
    animation: 'slide-up',
    animationIntensity: 2,
    highlightScale: 1.1,
  },
  {
    id: 'podcast-focus',
    name: 'Podcast Focus',
    presetKey: 'podcast-focus',
    category: 'Podcast',
    description: 'Active word slides in with calm emphasis.',
    fontFamily: 'Montserrat',
    fontSize: 50,
    fontWeight: '700',
    letterSpacing: 0.6,
    lineHeight: 1.25,
    casing: 'preserve',
    textColor: '#CBD5E1',
    activeWordColor: '#FACC15',
    inactiveWordOpacity: 0.5,
    strokeColor: '#000000',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 8,
    shadowOffsetX: 1,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#020617',
    backgroundOpacity: 0.85,
    backgroundPaddingX: 18,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 76,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'active-color',
    animationIntensity: 3,
    highlightScale: 1.2,
  },

  // --- CINEMATIC ---
  {
    id: 'cinematic-bold',
    name: 'Cinematic Bold',
    presetKey: 'cinematic-bold',
    category: 'Cinematic',
    description: 'Bold cinematic presence with restrained pop.',
    fontFamily: 'Playfair Display',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 1,
    lineHeight: 1.25,
    casing: 'preserve',
    textColor: '#FFFBEB',
    activeWordColor: '#FDE68A',
    secondaryColor: '#F59E0B',
    strokeColor: '#000000',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#1C1917',
    backgroundOpacity: 0.75,
    backgroundPaddingX: 20,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'pop',
    animationIntensity: 2.5,
    highlightScale: 1.15,
  },
  {
    id: 'cinematic-focus',
    name: 'Cinematic Focus',
    presetKey: 'cinematic-focus',
    category: 'Cinematic',
    description: 'Focused cinematic with soft active scaling.',
    fontFamily: 'Cinzel',
    fontSize: 50,
    fontWeight: '700',
    letterSpacing: 1.5,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#FFF7ED',
    activeWordColor: '#FDBA74',
    secondaryColor: '#EA580C',
    strokeColor: '#000000',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 10,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 80,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'fade',
    animationIntensity: 2,
    highlightScale: 1.15,
  },
  {
    id: 'film-subtitle',
    name: 'Film Subtitle',
    presetKey: 'film-subtitle',
    category: 'Cinematic',
    description: 'Film festival subtitle — elegant and understated.',
    fontFamily: 'Inter',
    fontSize: 42,
    fontWeight: '500',
    letterSpacing: 0.3,
    lineHeight: 1.4,
    casing: 'preserve',
    textColor: '#F1F5F9',
    activeWordColor: '#F1F5F9',
    strokeColor: '#000000',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 6,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.6,
    backgroundPaddingX: 14,
    backgroundPaddingY: 6,
    backgroundBorderRadius: 6,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 86,
    alignment: 'center',
    maxWordsPerLine: 8,
    animation: 'cinematic',
    animationIntensity: 1,
    highlightScale: 1,
  },
  {
    id: 'dramatic-highlight',
    name: 'Dramatic Highlight',
    presetKey: 'dramatic-highlight',
    category: 'Cinematic',
    description: 'Dramatic quote highlight with golden active word.',
    fontFamily: 'Playfair Display',
    fontSize: 54,
    fontWeight: '700',
    letterSpacing: 0.8,
    lineHeight: 1.25,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#FACC15',
    secondaryColor: '#854D0E',
    strokeColor: '#000000',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowBlur: 14,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasLightingGlow: true,
    lightingGlowColor: '#F59E0B',
    lightingGlowRadius: 20,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 74,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'glow',
    animationIntensity: 3,
    highlightScale: 1.2,
  },
  {
    id: 'cinematic-minimal-bold',
    name: 'Cinematic Minimal Bold',
    presetKey: 'cinematic-minimal-bold',
    category: 'Cinematic',
    description: 'Minimal cinematic with bold active word punch.',
    fontFamily: 'Inter',
    fontSize: 46,
    fontWeight: '700',
    letterSpacing: 0.4,
    lineHeight: 1.35,
    casing: 'preserve',
    textColor: '#E2E8F0',
    activeWordColor: '#38BDF8',
    strokeColor: '#000000',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 82,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'slide-up',
    animationIntensity: 1.5,
    highlightScale: 1.15,
  },

  // --- BUSINESS ---
  {
    id: 'business-clean',
    name: 'Business Clean',
    presetKey: 'business-clean',
    category: 'Business',
    description: 'STYLE 07 — Professional clean for decks and pitches.',
    fontFamily: 'Inter',
    fontSize: 44,
    fontWeight: '600',
    letterSpacing: 0.3,
    lineHeight: 1.35,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#0F172A',
    hasHighlightBox: true,
    highlightBoxColor: '#FDE68A',
    highlightBoxTextColor: '#0F172A',
    highlightBoxPaddingX: 8,
    highlightBoxPaddingY: 3,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1,
    strokeColor: '#000000',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.7)',
    shadowBlur: 6,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 80,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'word-highlight',
    animationIntensity: 2,
    highlightScale: 1.05,
  },
  {
    id: 'corporate-bold',
    name: 'Corporate Bold',
    presetKey: 'corporate-bold',
    category: 'Business',
    description: 'Corporate authority with controlled pop.',
    fontFamily: 'Montserrat',
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#0EA5E9',
    secondaryColor: '#0284C7',
    strokeColor: '#0F172A',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasBackgroundPill: true,
    backgroundColor: '#FFFFFF',
    backgroundOpacity: 0.95,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'active-color',
    animationIntensity: 3,
    highlightScale: 1.15,
  },
  {
    id: 'executive',
    name: 'Executive',
    presetKey: 'executive',
    category: 'Business',
    description: 'Executive serif with gold active emphasis.',
    fontFamily: 'Playfair Display',
    fontSize: 50,
    fontWeight: '700',
    letterSpacing: 1,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#1E293B',
    activeWordColor: '#B45309',
    secondaryColor: '#F59E0B',
    strokeColor: '#FFFFFF',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.15)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#FFFBEB',
    backgroundOpacity: 0.95,
    backgroundPaddingX: 18,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'fade',
    animationIntensity: 2,
    highlightScale: 1.15,
  },
  {
    id: 'marketing-focus',
    name: 'Marketing Focus',
    presetKey: 'marketing-focus',
    category: 'Business',
    description: 'Marketing hook with number-friendly emphasis.',
    fontFamily: 'Poppins',
    fontSize: 54,
    fontWeight: '800',
    letterSpacing: 0.8,
    lineHeight: 1.2,
    casing: 'preserve',
    textColor: '#0F172A',
    activeWordColor: '#7C3AED',
    secondaryColor: '#A78BFA',
    strokeColor: '#FFFFFF',
    strokeWidth: 4,
    hasShadow: true,
    shadowColor: 'rgba(124,58,237,0.3)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#EDE9FE',
    backgroundOpacity: 0.95,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 76,
    alignment: 'center',
    maxWordsPerLine: 4,
    animation: 'pop',
    animationIntensity: 3.5,
    highlightScale: 1.25,
  },
  {
    id: 'professional-highlight',
    name: 'Professional Highlight',
    presetKey: 'professional-highlight',
    category: 'Business',
    description: 'Professional highlight bar under active keyword.',
    fontFamily: 'Inter',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: 0.4,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#334155',
    activeWordColor: '#0F172A',
    hasHighlightBox: true,
    highlightBoxColor: '#BAE6FD',
    highlightBoxTextColor: '#0C4A6E',
    highlightBoxPaddingX: 9,
    highlightBoxPaddingY: 4,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1,
    strokeColor: '#FFFFFF',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.12)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#F8FAFC',
    backgroundOpacity: 0.95,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'highlight-box',
    animationIntensity: 2.5,
    highlightScale: 1.05,
  },

  // --- EDUCATIONAL ---
  {
    id: 'education-clean',
    name: 'Education Clean',
    presetKey: 'education-clean',
    category: 'Educational',
    description: 'STYLE 08 — Readable lesson style with clear spacing.',
    fontFamily: 'Inter',
    fontSize: 46,
    fontWeight: '600',
    letterSpacing: 0.3,
    lineHeight: 1.4,
    casing: 'preserve',
    textColor: '#0F172A',
    activeWordColor: '#1E40AF',
    secondaryColor: '#DBEAFE',
    strokeColor: '#FFFFFF',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.15)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#EFF6FF',
    backgroundOpacity: 0.96,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'slide-up',
    animationIntensity: 1.5,
    highlightScale: 1.1,
  },
  {
    id: 'lesson-focus',
    name: 'Lesson Focus',
    presetKey: 'lesson-focus',
    category: 'Educational',
    description: 'Focus word scales with calm slide-up.',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: 0.4,
    lineHeight: 1.35,
    casing: 'preserve',
    textColor: '#334155',
    activeWordColor: '#0F172A',
    hasHighlightBox: true,
    highlightBoxColor: '#FDE68A',
    highlightBoxTextColor: '#92400E',
    highlightBoxPaddingX: 8,
    highlightBoxPaddingY: 3,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1,
    strokeColor: '#FFFFFF',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.12)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#FFFFFF',
    backgroundOpacity: 0.96,
    backgroundPaddingX: 18,
    backgroundPaddingY: 9,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'word-pop',
    animationIntensity: 2.5,
    highlightScale: 1.15,
  },
  {
    id: 'keyword-highlight',
    name: 'Keyword Highlight',
    presetKey: 'keyword-highlight',
    category: 'Educational',
    description: 'Keyword marker for explainer videos.',
    fontFamily: 'Inter',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: 0.4,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#1E293B',
    activeWordColor: '#FFFFFF',
    hasHighlightBox: true,
    highlightBoxColor: '#0EA5E9',
    highlightBoxTextColor: '#FFFFFF',
    highlightBoxPaddingX: 9,
    highlightBoxPaddingY: 4,
    highlightBoxRadius: 6,
    highlightBoxOpacity: 1,
    strokeColor: '#FFFFFF',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.12)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#F8FAFC',
    backgroundOpacity: 0.95,
    backgroundPaddingX: 18,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'highlight-box',
    animationIntensity: 2,
    highlightScale: 1.05,
  },
  {
    id: 'explainer',
    name: 'Explainer',
    presetKey: 'explainer',
    category: 'Educational',
    description: 'Explainer step with karaoke tracking.',
    fontFamily: 'Inter',
    fontSize: 46,
    fontWeight: '600',
    letterSpacing: 0.3,
    lineHeight: 1.4,
    casing: 'preserve',
    textColor: '#64748B',
    activeWordColor: '#0F172A',
    secondaryColor: '#CBD5E1',
    inactiveWordOpacity: 0.45,
    strokeColor: '#FFFFFF',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.12)',
    shadowBlur: 6,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#FFFFFF',
    backgroundOpacity: 0.96,
    backgroundPaddingX: 18,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 12,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 78,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'karaoke',
    animationIntensity: 2,
    highlightScale: 1.1,
  },
  {
    id: 'knowledge-pop',
    name: 'Knowledge Pop',
    presetKey: 'knowledge-pop',
    category: 'Educational',
    description: 'Pop emphasis for key facts.',
    fontFamily: 'Poppins',
    fontSize: 50,
    fontWeight: '800',
    letterSpacing: 0.5,
    lineHeight: 1.3,
    casing: 'preserve',
    textColor: '#0F172A',
    activeWordColor: '#DC2626',
    secondaryColor: '#FCA5A5',
    strokeColor: '#FFFFFF',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(220,38,38,0.2)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    hasBackgroundPill: true,
    backgroundColor: '#FEF2F2',
    backgroundOpacity: 0.96,
    backgroundPaddingX: 18,
    backgroundPaddingY: 9,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 76,
    alignment: 'center',
    maxWordsPerLine: 5,
    animation: 'pop',
    animationIntensity: 3,
    highlightScale: 1.2,
  },

  // --- MINIMAL ---
  {
    id: 'minimal-white',
    name: 'Minimal White',
    presetKey: 'minimal-white',
    category: 'Minimal',
    description: 'Ultra-clean white with hairline stroke.',
    fontFamily: 'Inter',
    fontSize: 42,
    fontWeight: '500',
    letterSpacing: 0.2,
    lineHeight: 1.4,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.6,
    backgroundPaddingX: 14,
    backgroundPaddingY: 6,
    backgroundBorderRadius: 6,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 86,
    alignment: 'center',
    maxWordsPerLine: 8,
    animation: 'fade',
    animationIntensity: 1,
    highlightScale: 1,
  },
  {
    id: 'minimal-bold',
    name: 'Minimal Bold',
    presetKey: 'minimal-bold',
    category: 'Minimal',
    description: 'Minimal but bold with subtle scale.',
    fontFamily: 'Inter',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: 0.3,
    lineHeight: 1.35,
    casing: 'preserve',
    textColor: '#F8FAFC',
    activeWordColor: '#F8FAFC',
    strokeColor: '#000000',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    hasBackgroundPill: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPaddingX: 16,
    backgroundPaddingY: 8,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 84,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'pop',
    animationIntensity: 1.5,
    highlightScale: 1.1,
  },
  {
    id: 'modern-clean',
    name: 'Modern Clean',
    presetKey: 'modern-clean',
    category: 'Minimal',
    description: 'Modern clean sans with soft pill.',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 46,
    fontWeight: '600',
    letterSpacing: 0.3,
    lineHeight: 1.35,
    casing: 'preserve',
    textColor: '#0F172A',
    activeWordColor: '#0F172A',
    strokeColor: '#FFFFFF',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.12)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#F8FAFC',
    backgroundOpacity: 0.96,
    backgroundPaddingX: 18,
    backgroundPaddingY: 9,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 84,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'slide-up',
    animationIntensity: 1.5,
    highlightScale: 1.05,
  },
  {
    id: 'elegant',
    name: 'Elegant',
    presetKey: 'elegant',
    category: 'Minimal',
    description: 'Elegant serif for premium minimal.',
    fontFamily: 'Playfair Display',
    fontSize: 48,
    fontWeight: '600',
    letterSpacing: 0.8,
    lineHeight: 1.35,
    casing: 'preserve',
    textColor: '#1E293B',
    activeWordColor: '#1E293B',
    strokeColor: '#FFFFFF',
    strokeWidth: 2,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.12)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#FFFFFF',
    backgroundOpacity: 0.96,
    backgroundPaddingX: 18,
    backgroundPaddingY: 10,
    backgroundBorderRadius: 10,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 84,
    alignment: 'center',
    maxWordsPerLine: 6,
    animation: 'fade',
    animationIntensity: 1,
    highlightScale: 1,
  },
  {
    id: 'clean-subtitle-pro',
    name: 'Clean Subtitle Pro',
    presetKey: 'clean-subtitle-pro',
    category: 'Minimal',
    description: 'Pro clean subtitle with balanced wrapping.',
    fontFamily: 'Inter',
    fontSize: 42,
    fontWeight: '600',
    letterSpacing: 0.2,
    lineHeight: 1.4,
    casing: 'preserve',
    textColor: '#FFFFFF',
    activeWordColor: '#FACC15',
    strokeColor: '#000000',
    strokeWidth: 3,
    hasShadow: true,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    hasBackgroundPill: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.65,
    backgroundPaddingX: 16,
    backgroundPaddingY: 6,
    backgroundBorderRadius: 8,
    position: 'bottom',
    xOffsetPercent: 50,
    yOffsetPercent: 86,
    alignment: 'center',
    maxWordsPerLine: 8,
    animation: 'clean-sub',
    animationIntensity: 1,
    highlightScale: 1,
  },
];
