export interface VisualAssetCard {
  id: string;
  name: string;
  category: string;
  subCategory?: string;
  thumbnailGradient: string;
  previewSvgType: string;
  accentColor: string;
  badge?: 'PRO' | 'HOT' | 'NEW' | 'TRENDING';
  description?: string;
}

// 20 Video Transitions with CapCut-style Visual Metadata
export const TRANSITION_VISUAL_THUMBNAILS: Record<string, {
  name: string;
  category: string;
  subCategory: string;
  badge?: 'PRO' | 'HOT' | 'NEW' | 'TRENDING';
  bgGradient: string;
  accentColor: string;
  iconType: string;
  previewUrl?: string;
}> = {
  cut: {
    name: 'Hard Cut',
    category: 'basic',
    subCategory: 'Basic',
    bgGradient: 'from-slate-900 via-gray-800 to-zinc-900',
    accentColor: '#94A3B8',
    iconType: 'cut',
  },
  crossfade: {
    name: 'Cross Dissolve',
    category: 'fade',
    subCategory: 'Trending',
    badge: 'TRENDING',
    bgGradient: 'from-blue-950 via-indigo-900 to-purple-950',
    accentColor: '#38BDF8',
    iconType: 'crossfade',
  },
  'fade-in': {
    name: 'Fade In',
    category: 'fade',
    subCategory: 'Basic',
    bgGradient: 'from-black via-zinc-900 to-slate-900',
    accentColor: '#FACC15',
    iconType: 'fade-in',
  },
  'fade-out': {
    name: 'Fade Out',
    category: 'fade',
    subCategory: 'Basic',
    bgGradient: 'from-slate-900 via-zinc-900 to-black',
    accentColor: '#F43F5E',
    iconType: 'fade-out',
  },
  'dip-black': {
    name: 'Dip to Black',
    category: 'fade',
    subCategory: 'Classic',
    badge: 'HOT',
    bgGradient: 'from-neutral-950 via-black to-neutral-900',
    accentColor: '#E2E8F0',
    iconType: 'dip-black',
  },
  'dip-white': {
    name: 'Dip to White',
    category: 'fade',
    subCategory: 'Light',
    badge: 'PRO',
    bgGradient: 'from-amber-200 via-white to-orange-100 text-black',
    accentColor: '#F59E0B',
    iconType: 'dip-white',
  },
  'whip-left': {
    name: 'Whip Left',
    category: 'motion',
    subCategory: 'Trending',
    badge: 'HOT',
    bgGradient: 'from-cyan-950 via-teal-900 to-slate-900',
    accentColor: '#06B6D4',
    iconType: 'whip-left',
  },
  'whip-right': {
    name: 'Whip Right',
    category: 'motion',
    subCategory: 'Trending',
    bgGradient: 'from-teal-950 via-cyan-900 to-slate-900',
    accentColor: '#14B8A6',
    iconType: 'whip-right',
  },
  'push-up': {
    name: 'Push Up',
    category: 'slide',
    subCategory: 'Fast Swipe',
    badge: 'TRENDING',
    bgGradient: 'from-indigo-950 via-purple-900 to-slate-900',
    accentColor: '#818CF8',
    iconType: 'push-up',
  },
  'slide-left': {
    name: 'Slide Left',
    category: 'slide',
    subCategory: 'Fast Swipe',
    bgGradient: 'from-sky-950 via-blue-900 to-slate-900',
    accentColor: '#38BDF8',
    iconType: 'slide-left',
  },
  'slide-right': {
    name: 'Slide Right',
    category: 'slide',
    subCategory: 'Fast Swipe',
    bgGradient: 'from-blue-950 via-sky-900 to-slate-900',
    accentColor: '#60A5FA',
    iconType: 'slide-right',
  },
  'iris-circle': {
    name: 'Iris Circle',
    category: 'wipe',
    subCategory: 'Camera',
    badge: 'PRO',
    bgGradient: 'from-emerald-950 via-teal-900 to-slate-900',
    accentColor: '#10B981',
    iconType: 'iris-circle',
  },
  'wipe-right': {
    name: 'Wavy Split',
    category: 'wipe',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-purple-950 via-fuchsia-900 to-slate-900',
    accentColor: '#C084FC',
    iconType: 'wipe-right',
  },
  'zoom-in': {
    name: 'Zoom In',
    category: 'zoom',
    subCategory: 'Trending',
    badge: 'HOT',
    bgGradient: 'from-amber-950 via-orange-900 to-slate-900',
    accentColor: '#FBBF24',
    iconType: 'zoom-in',
  },
  'zoom-out': {
    name: 'Zoom Out',
    category: 'zoom',
    subCategory: 'Classic',
    bgGradient: 'from-orange-950 via-amber-900 to-slate-900',
    accentColor: '#F97316',
    iconType: 'zoom-out',
  },
  'spin-cw': {
    name: 'Spin CW',
    category: 'motion',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-violet-950 via-purple-900 to-indigo-950',
    accentColor: '#A78BFA',
    iconType: 'spin-cw',
  },
  'glitch-flash': {
    name: 'Camera Blink',
    category: 'creative',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-rose-950 via-pink-900 to-cyan-950',
    accentColor: '#F43F5E',
    iconType: 'glitch-flash',
  },
  'ripple-wave': {
    name: 'Horizon Split',
    category: 'creative',
    subCategory: 'Summer',
    badge: 'HOT',
    bgGradient: 'from-cyan-950 via-sky-900 to-emerald-950',
    accentColor: '#22D3EE',
    iconType: 'ripple-wave',
  },
  'light-leak': {
    name: 'Light Leak',
    category: 'cinematic',
    subCategory: 'Light',
    badge: 'PRO',
    bgGradient: 'from-amber-900 via-orange-800 to-red-950',
    accentColor: '#FDE047',
    iconType: 'light-leak',
  },
  'lens-flare': {
    name: 'Comparison II',
    category: 'cinematic',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-yellow-950 via-amber-900 to-sky-950',
    accentColor: '#FEF08A',
    iconType: 'lens-flare',
  },
};

// 20 Video Effects & Shaders
export const EFFECT_VISUAL_THUMBNAILS: Record<string, {
  name: string;
  category: string;
  subCategory: string;
  badge?: 'PRO' | 'HOT' | 'NEW' | 'TRENDING';
  bgGradient: string;
  accentColor: string;
  iconType: string;
}> = {
  chromatic: {
    name: 'Turbulence II',
    category: 'glitch',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-rose-950 via-indigo-900 to-cyan-950',
    accentColor: '#00F0FF',
    iconType: 'chromatic',
  },
  vhs: {
    name: 'Ice Cube',
    category: 'retro',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-cyan-950 via-blue-900 to-indigo-950',
    accentColor: '#38BDF8',
    iconType: 'vhs',
  },
  glow: {
    name: 'Wave Shake',
    category: 'light',
    subCategory: 'Trending',
    badge: 'HOT',
    bgGradient: 'from-pink-950 via-purple-900 to-blue-950',
    accentColor: '#F472B6',
    iconType: 'glow',
  },
  edge: {
    name: 'Magic Cube 3',
    category: 'stylize',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-sky-900 via-indigo-950 to-neutral-950',
    accentColor: '#E0E7FF',
    iconType: 'edge',
  },
  rgb_split: {
    name: 'RGB Split',
    category: 'glitch',
    subCategory: 'Glitch',
    badge: 'PRO',
    bgGradient: 'from-red-950 via-purple-900 to-cyan-950',
    accentColor: '#FF0055',
    iconType: 'rgb_split',
  },
  vignette: {
    name: 'Fade In',
    category: 'lens',
    subCategory: 'Basic',
    bgGradient: 'from-neutral-900 via-zinc-950 to-black',
    accentColor: '#94A3B8',
    iconType: 'vignette',
  },
  grain: {
    name: 'Zoom Out',
    category: 'retro',
    subCategory: 'Basic',
    bgGradient: 'from-stone-900 via-zinc-900 to-neutral-950',
    accentColor: '#D6D3D1',
    iconType: 'grain',
  },
  blur: {
    name: 'Shake Away',
    category: 'blur',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-slate-900 via-blue-950 to-indigo-950',
    accentColor: '#93C5FD',
    iconType: 'blur',
  },
  motion_blur: {
    name: 'Motion Blur',
    category: 'blur',
    subCategory: 'Trending',
    badge: 'HOT',
    bgGradient: 'from-indigo-950 via-cyan-900 to-slate-900',
    accentColor: '#67E8F9',
    iconType: 'motion_blur',
  },
  bloom: {
    name: 'Bloom Highlight',
    category: 'light',
    subCategory: 'Light',
    badge: 'PRO',
    bgGradient: 'from-amber-950 via-yellow-900 to-orange-950',
    accentColor: '#FDE047',
    iconType: 'bloom',
  },
  mirror: {
    name: 'Mirror Reflection',
    category: 'distort',
    subCategory: 'Stylize',
    bgGradient: 'from-teal-950 via-cyan-900 to-blue-950',
    accentColor: '#2DD4BF',
    iconType: 'mirror',
  },
  scanlines: {
    name: 'CRT Scanlines',
    category: 'retro',
    subCategory: 'Retro',
    bgGradient: 'from-green-950 via-emerald-900 to-slate-950',
    accentColor: '#4ADE80',
    iconType: 'scanlines',
  },
  prism: {
    name: 'Prism Refraction',
    category: 'light',
    subCategory: 'Light',
    badge: 'PRO',
    bgGradient: 'from-fuchsia-950 via-pink-900 to-cyan-950',
    accentColor: '#E879F9',
    iconType: 'prism',
  },
  thermal: {
    name: 'Thermal Heatmap',
    category: 'color',
    subCategory: 'Color',
    badge: 'HOT',
    bgGradient: 'from-blue-900 via-yellow-600 to-red-600',
    accentColor: '#F97316',
    iconType: 'thermal',
  },
  solarize: {
    name: 'Solarize Invert',
    category: 'color',
    subCategory: 'Color',
    bgGradient: 'from-purple-900 via-amber-600 to-cyan-700',
    accentColor: '#A855F7',
    iconType: 'solarize',
  },
  radial_blur: {
    name: 'Radial Zoom Blur',
    category: 'blur',
    subCategory: 'Trending',
    badge: 'PRO',
    bgGradient: 'from-orange-950 via-amber-900 to-slate-950',
    accentColor: '#FB923C',
    iconType: 'radial_blur',
  },
  comic: {
    name: 'Comic Pop-Art',
    category: 'stylize',
    subCategory: 'Stylize',
    badge: 'PRO',
    bgGradient: 'from-yellow-900 via-red-900 to-indigo-950',
    accentColor: '#FACC15',
    iconType: 'comic',
  },
  halftone: {
    name: 'Halftone Dots',
    category: 'stylize',
    subCategory: 'Retro',
    bgGradient: 'from-neutral-900 via-stone-800 to-zinc-950',
    accentColor: '#A3A3A3',
    iconType: 'halftone',
  },
  pixelate: {
    name: 'Pixelate 8-Bit',
    category: 'distort',
    subCategory: 'Retro',
    bgGradient: 'from-emerald-950 via-cyan-900 to-purple-950',
    accentColor: '#34D399',
    iconType: 'pixelate',
  },
  sharpen: {
    name: 'Sharpen HDR',
    category: 'color',
    subCategory: 'Basic',
    bgGradient: 'from-slate-900 via-sky-950 to-slate-900',
    accentColor: '#38BDF8',
    iconType: 'sharpen',
  },
};

// 20 Filters & Color Grades
export const FILTER_VISUAL_THUMBNAILS: Record<string, {
  name: string;
  subCategory: string;
  badge?: 'PRO' | 'HOT' | 'NEW' | 'TRENDING';
  bgGradient: string;
  accentColor: string;
  cssFilter: string;
}> = {
  '4k-clean': {
    name: '4K Clean',
    subCategory: 'Featured',
    badge: 'PRO',
    bgGradient: 'from-emerald-800 via-green-700 to-teal-900',
    accentColor: '#10B981',
    cssFilter: 'contrast(1.15) saturate(1.2) brightness(1.05)',
  },
  'fresh-lime': {
    name: 'Fresh Lime',
    subCategory: 'Featured',
    badge: 'PRO',
    bgGradient: 'from-lime-800 via-emerald-700 to-sky-900',
    accentColor: '#84CC16',
    cssFilter: 'hue-rotate(20deg) saturate(1.3) contrast(1.1)',
  },
  '8k-cinematic': {
    name: '8K Cinematic',
    subCategory: 'Featured',
    badge: 'PRO',
    bgGradient: 'from-stone-800 via-amber-900 to-neutral-950',
    accentColor: '#F59E0B',
    cssFilter: 'contrast(1.25) saturate(1.1) brightness(0.98)',
  },
  'universal-sunset': {
    name: 'Universal Sunset',
    subCategory: 'Featured',
    badge: 'PRO',
    bgGradient: 'from-orange-700 via-rose-800 to-purple-950',
    accentColor: '#FB923C',
    cssFilter: 'sepia(0.3) saturate(1.6) hue-rotate(-15deg)',
  },
  'faded-street': {
    name: 'Faded Street',
    subCategory: 'Featured',
    badge: 'HOT',
    bgGradient: 'from-stone-700 via-neutral-800 to-amber-950',
    accentColor: '#D97706',
    cssFilter: 'sepia(0.2) contrast(0.9) brightness(1.05)',
  },
  'brown-warmth': {
    name: 'Brown Warmth',
    subCategory: 'Featured',
    bgGradient: 'from-amber-900 via-yellow-950 to-neutral-900',
    accentColor: '#B45309',
    cssFilter: 'sepia(0.4) saturate(1.2) contrast(1.15)',
  },
  'teal-orange': {
    name: 'Teal & Orange',
    subCategory: 'Hits',
    badge: 'HOT',
    bgGradient: 'from-cyan-900 via-teal-950 to-orange-800',
    accentColor: '#F97316',
    cssFilter: 'contrast(1.3) saturate(1.3) hue-rotate(-10deg)',
  },
  'moody-dark': {
    name: 'Moody Dark',
    subCategory: 'Hits',
    badge: 'PRO',
    bgGradient: 'from-slate-950 via-zinc-900 to-neutral-950',
    accentColor: '#64748B',
    cssFilter: 'brightness(0.85) contrast(1.4) saturate(0.8)',
  },
  'cyber-neon': {
    name: 'Cyber Neon',
    subCategory: 'CCD',
    badge: 'PRO',
    bgGradient: 'from-purple-900 via-fuchsia-950 to-cyan-900',
    accentColor: '#00F0FF',
    cssFilter: 'contrast(1.4) saturate(2.0) hue-rotate(90deg)',
  },
  'bleach-bypass': {
    name: 'Bleach Bypass',
    subCategory: 'Hits',
    bgGradient: 'from-zinc-800 via-stone-900 to-neutral-950',
    accentColor: '#E2E8F0',
    cssFilter: 'contrast(1.5) saturate(0.4) brightness(1.1)',
  },
  'vintage-kodachrome': {
    name: 'Vintage Kodachrome',
    subCategory: 'Life',
    badge: 'HOT',
    bgGradient: 'from-amber-800 via-red-900 to-yellow-950',
    accentColor: '#EF4444',
    cssFilter: 'sepia(0.35) contrast(1.2) saturate(1.4)',
  },
  'bw-noir': {
    name: 'B&W Film Noir',
    subCategory: 'Life',
    bgGradient: 'from-white via-gray-500 to-black',
    accentColor: '#FFFFFF',
    cssFilter: 'grayscale(1.0) contrast(1.5)',
  },
  'forest-emerald': {
    name: 'Forest Emerald',
    subCategory: 'Landscape',
    badge: 'PRO',
    bgGradient: 'from-emerald-900 via-teal-950 to-green-900',
    accentColor: '#10B981',
    cssFilter: 'hue-rotate(30deg) saturate(1.4) contrast(1.2)',
  },
  'golden-hour': {
    name: 'Golden Hour',
    subCategory: 'Landscape',
    badge: 'HOT',
    bgGradient: 'from-yellow-700 via-amber-800 to-orange-950',
    accentColor: '#FACC15',
    cssFilter: 'sepia(0.4) saturate(1.5) brightness(1.08)',
  },
  'pastel-dream': {
    name: 'Pastel Dream',
    subCategory: 'Photo Booth',
    bgGradient: 'from-pink-800 via-purple-900 to-sky-900',
    accentColor: '#F472B6',
    cssFilter: 'brightness(1.15) contrast(0.9) saturate(1.2)',
  },
  'crisp-clean': {
    name: 'Crisp Clean',
    subCategory: 'Featured',
    bgGradient: 'from-sky-800 via-blue-900 to-slate-950',
    accentColor: '#38BDF8',
    cssFilter: 'contrast(1.2) brightness(1.04) saturate(1.15)',
  },
  'arctic-chill': {
    name: 'Arctic Chill',
    subCategory: 'Landscape',
    bgGradient: 'from-cyan-900 via-sky-950 to-slate-950',
    accentColor: '#67E8F9',
    cssFilter: 'hue-rotate(180deg) saturate(0.9) contrast(1.2)',
  },
  'desert-dust': {
    name: 'Desert Dust',
    subCategory: 'Landscape',
    bgGradient: 'from-amber-800 via-orange-900 to-stone-950',
    accentColor: '#D97706',
    cssFilter: 'sepia(0.5) contrast(1.1) saturate(1.2)',
  },
  'urban-steel': {
    name: 'Urban Steel',
    subCategory: 'Hits',
    bgGradient: 'from-slate-800 via-gray-900 to-zinc-950',
    accentColor: '#94A3B8',
    cssFilter: 'saturate(0.5) contrast(1.3) brightness(0.95)',
  },
  'super-vivid': {
    name: 'Super Vivid',
    subCategory: 'Featured',
    badge: 'HOT',
    bgGradient: 'from-fuchsia-800 via-purple-900 to-cyan-900',
    accentColor: '#E879F9',
    cssFilter: 'saturate(2.2) contrast(1.3) brightness(1.05)',
  },
};
